// Generated by The IOTIFT Compiler - ESP32 Ready
// Target: esp32

#include "Arduino.h"
#include <math.h>


// ────────── Pin Definitions ──────────
#define R_PIN 13
#define G_PIN 12
#define B_PIN 14


// ────────── Global State ──────────
float r = 0.0;
float g = 0.0;
float b = 0.0;
float t = 0.0;
unsigned long _every_0_last = 0;


// ────────── Handlers ──────────
void handle_every_0() {
  unsigned long now = millis();
  if (now - _every_0_last >= 10UL) {
      _every_0_last = now;
      t = millis();
      r = (255 - (127.5 + (127.5 * sin((t * 0.001)))));
      g = (255 - (127.5 + (127.5 * sin(((t * 0.001) + 2.094)))));
      b = (255 - (127.5 + (127.5 * sin(((t * 0.001) + 4.189)))));
      ledcWrite(0, r);
      ledcWrite(1, g);
      ledcWrite(2, b);
  }
}


// ────────── Setup ──────────
void setup() {
  Serial.begin(115200);
  pinMode(R_PIN, OUTPUT);
  pinMode(G_PIN, OUTPUT);
  pinMode(B_PIN, OUTPUT);
  ledcSetup(0, 5000, 8);
  ledcAttachPin(13, 0);
  ledcSetup(1, 5000, 8);
  ledcAttachPin(12, 1);
  ledcSetup(2, 5000, 8);
  ledcAttachPin(14, 2);
  _every_0_last = millis();
}


// ────────── Main Loop ──────────
void loop() {
  handle_every_0();
  yield();
}
