// Generated by IOTIFT - ESP32 Arduino Production Ready
// Target: esp32

#include "Arduino.h"


// ────────── Global State ──────────
float r;
float g;
float x;
float y;


// ────────── Setup ──────────
void setup() {
  Serial.begin(115200);
}


// ────────── Main Loop ──────────
void loop() {
      float t = millis();
      float a = 1.0;
      float b = 2.0;
      float z = 3.0;
      r = sin(t * 0.001);
      g = sin(t * 0.001 + 2.094);
      x = sqrt(pow(a, 2) + pow(b, 2));
      y = floor(ceil(abs(z)));
  yield();
}
