// ════════════════════════════════════════
//  Generated by IOTIFT compiler
//  Target: esp32
// ════════════════════════════════════════

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

// ── Pin Definitions ──
#define LED_PIN 12
#define BTN_PIN 5
#define TEMP_PIN 34
#define FAN_PIN 18

// ── Global State ──
int count = 0;
float tempVal = 0.0;
int fanOn = 0;
extern void esp_restart(void);
int _last_BTN_state = 0;
int _every_0_active = 1;
uint32_t _every_0_last = 0;
uint32_t _every_1_last = 0;

// ── Time ──
uint32_t millis() {
    // replace with platform millis
    return 0;
}

// ── HAL Stubs (replace with real HAL) ──
void gpio_set_level(int pin, int val) {}
int  gpio_get_level(int pin)          { return 0; }
void schedule_after(int pin, int val, int ms) {}

// ── Event & Timer Handlers ──
void handle_BTN_press() {
    int _state = gpio_get_level(BTN_PIN);
    if (_state == 1 && _last_BTN_state == 0) {
        gpio_set_level(LED_PIN, 1);
        schedule_after(LED_PIN, 0, 200);
    }
    _last_BTN_state = _state;
}

void handle_BTN_release() {
    int _state = gpio_get_level(BTN_PIN);
    if (_state == 0 && _last_BTN_state == 1) {
        gpio_set_level(LED_PIN, 0);
    }
    _last_BTN_state = _state;
}

void handle_every_0() {
    if (_every_0_active) {
        if (esp_timer_get_time() / 1000 - _every_0_last >= 1000U) {
            _every_0_last = esp_timer_get_time() / 1000;
            count += 1;
            printf("%d\n", count);
            if ((count == 10)) {
    // stop ticker;
}
        }
    }
}

void handle_every_1() {
    if (esp_timer_get_time() / 1000 - _every_1_last >= 500U) {
        _every_1_last = esp_timer_get_time() / 1000;
        tempVal = 25.5;
    }
}

// ── User Functions ──
void user_loop() {
    if ((count == 100)) {
    esp_restart();
}
}

// ── Setup ──
void setup() {
    pinMode(LED_PIN, OUTPUT);
    pinMode(BTN_PIN, INPUT);
    pinMode(TEMP_PIN, INPUT);
    pinMode(FAN_PIN, OUTPUT);
}

// ── Main Loop ──
void loop() {
    handle_BTN_press();
    handle_BTN_release();
    handle_every_0();
    handle_every_1();
    user_loop();
}
